language: node_js

node_js:
- 8

branches:
  only:
  - master

install:
- npm install

script:
- npm test
- npm run example

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: __site__
  on:
    branch: master